Created a p tag>
jiajdo/jiatechtonicaexercises pull request #1
Opened 2023-07-19 20:27 UTC by jiajdo

2023-07-20 06:08 UTC, eatnumber1 commented
Can you adjust the pull request's title to reflect the goal you're trying to achieve?

2023-07-20 06:10 UTC, eatnumber1 commented on recipe/index.html
Looks like you have a typo in this commit? (the trailing '>'). Can you fix?

2023-07-21 20:31 UTC, jiajdo commented on recipe/index.html
Edited first 2 commit messages for typos and made each commit purpose more clear. Also edited pull request title.

2023-07-22 22:09 UTC, eatnumber1 requested changes
It's optional, as some projects require it and some don't, but it's considered good practice to keep the first line of your commit message under 50 characters.

You can see why in the way github renders the commit message for ef7d57dd2bec052afb29b0adc458cbc9e3fae5aa. Apparently github is more lax than 50 characters, but it still breaks the line at 110 characters.

So I'd recommend shortening the summary line of your message, and adding a short paragraph beneath if more detail is warranted.

2023-07-22 22:12 UTC, eatnumber1 requested changes

2023-07-22 22:12 UTC, eatnumber1 commented on recipe/index.html
> +        <p><b><a href = "https://www.spendwithpennies.com/classic-chicken-salad-recipe/">Chicken Salad</a></b></p>
This doesn't do what the commit message says... this bolds the recipe, it doesn't add it.

2023-07-24 14:51 UTC, jiajdo commented on recipe/index.html
> +        <p><b><a href = "https://www.spendwithpennies.com/classic-chicken-salad-recipe/">Chicken Salad</a></b></p>
Reworded commit message

2023-07-24 18:20 UTC, jiajdo commented
Shortened summary line in commit [a8da806](https://github.com/jiajdo/jiatechtonicaexercises/pull/1/commits/a8da80683f016f32cd49ae5463eb83a8d4591936) added more information about the commit in newline paragraph.

2023-07-25 06:04 UTC, eatnumber1 approved these changes

2023-07-25 16:31 UTC, merged